parameters:
  max_num_batched_tokens:
    name: "max-num-batched-tokens"
    enabled: true
    range:
      start: 4096
      end: 16384
      step: 2048 # do 1024 for more trials

  compilation_config: # Figure this out
    name: "compilation-config"
    enabled: false
    values:
      - "default"
      - "cuda_graphs"
      - "cuda_graphs_with_fallback"

settings:
  trial_interval: 30  # Time in seconds to wait between trials
  
